on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y g++ make libgtest-dev cmake

    - name: Build and install Google Test
      run: |
        cd /usr/src/googletest
        cmake -DCMAKE_CXX_STANDARD=14 .
        make
        cp lib/*.a /usr/lib
        cp -r googletest/include/gtest /usr/include
        cp -r googlemock/include/gmock /usr/include

    - name: Build all apps
      run: make
