on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    container: ubuntu:latest

    steps:
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y clang-tidy

    - name: Lint
      run: |
        for app in apps/*; do
          if [ -d "$app" ]; then
            echo "Linting $app"
            clang-tidy $app/*.cpp -- -std=c++14
          fi
        done
